# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ceaee886dc90223aa0d623d0fbd2e1b0e878934931ccf7e1e23d48b3805747fe9808681c413a4cce3fd2baf4005f4412840b3fc00e62a86c6104dc73f01ea30

test:
  secret_key_base: b3b73050708b283e11a05e3a945fd6dad78dbe4912ecc4040ce64c8422be4a25e77942c81767d42d515d64626f0b496b537b3ee343647d5e7468c8ca75b4def9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
